name: 'Chromatic'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-readme:
    name: Check if only README.md changed
    runs-on: ubuntu-latest
    outputs:
      README_ONLY_CHANGED: ${{steps.check.outputs.README_ONLY_CHANGED}}
    steps:
      - name: Check code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if only README.md changed
        id: check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -v 'README.md' | grep -q '.'; then
            echo "README_ONLY_CHANGED=false" >> $GITHUB_ENV
            echo "README_ONLY_CHANGED=false" >> $GITHUB_OUTPUT
          else 
            echo "README_ONLY_CHANGED=true" >> $GITHUB_ENV
            echo "README_ONLY_CHANGED=true" >> $GITHUB_OUTPUT
          fi

  chromatic:
    name: Run Chromatic
    needs: check-readme # check-readme job이 실행 된 후에 실행
    if: needs.check-readme.outputs.README_ONLY_CHANGED == 'false' # README_ONLY_CHANGED가 false이어야만 아래 코드가 실행
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Install dependencies
        # ⚠️ See your package manager's documentation for the  correct command to install dependencies in a CI environment.
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: npx lerna run build

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
